<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE GANGLIA_XML [
   <!ELEMENT GANGLIA_XML (GRID|CLUSTER|HOST)*>
      <!ATTLIST GANGLIA_XML VERSION CDATA #REQUIRED>
      <!ATTLIST GANGLIA_XML SOURCE CDATA #REQUIRED>
   <!ELEMENT GRID (CLUSTER | GRID | HOSTS | METRICS)*>
      <!ATTLIST GRID NAME CDATA #REQUIRED>
      <!ATTLIST GRID AUTHORITY CDATA #REQUIRED>
      <!ATTLIST GRID LOCALTIME CDATA #IMPLIED>
   <!ELEMENT CLUSTER (HOST | HOSTS | METRICS)*>
      <!ATTLIST CLUSTER NAME CDATA #REQUIRED>
      <!ATTLIST CLUSTER OWNER CDATA #IMPLIED>
      <!ATTLIST CLUSTER LATLONG CDATA #IMPLIED>
      <!ATTLIST CLUSTER URL CDATA #IMPLIED>
      <!ATTLIST CLUSTER LOCALTIME CDATA #REQUIRED>
   <!ELEMENT HOST (METRIC)*>
      <!ATTLIST HOST NAME CDATA #REQUIRED>
      <!ATTLIST HOST IP CDATA #REQUIRED>
      <!ATTLIST HOST LOCATION CDATA #IMPLIED>
      <!ATTLIST HOST TAGS CDATA #IMPLIED>
      <!ATTLIST HOST REPORTED CDATA #REQUIRED>
      <!ATTLIST HOST TN CDATA #IMPLIED>
      <!ATTLIST HOST TMAX CDATA #IMPLIED>
      <!ATTLIST HOST DMAX CDATA #IMPLIED>
      <!ATTLIST HOST GMOND_STARTED CDATA #IMPLIED>
   <!ELEMENT METRIC (EXTRA_DATA*)>
      <!ATTLIST METRIC NAME CDATA #REQUIRED>
      <!ATTLIST METRIC VAL CDATA #REQUIRED>
      <!ATTLIST METRIC TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRIC UNITS CDATA #IMPLIED>
      <!ATTLIST METRIC TN CDATA #IMPLIED>
      <!ATTLIST METRIC TMAX CDATA #IMPLIED>
      <!ATTLIST METRIC DMAX CDATA #IMPLIED>
      <!ATTLIST METRIC SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRIC SOURCE (gmond) 'gmond'>
   <!ELEMENT EXTRA_DATA (EXTRA_ELEMENT*)>
   <!ELEMENT EXTRA_ELEMENT EMPTY>
      <!ATTLIST EXTRA_ELEMENT NAME CDATA #REQUIRED>
      <!ATTLIST EXTRA_ELEMENT VAL CDATA #REQUIRED>
   <!ELEMENT HOSTS EMPTY>
      <!ATTLIST HOSTS UP CDATA #REQUIRED>
      <!ATTLIST HOSTS DOWN CDATA #REQUIRED>
      <!ATTLIST HOSTS SOURCE (gmond | gmetad) #REQUIRED>
   <!ELEMENT METRICS (EXTRA_DATA*)>
      <!ATTLIST METRICS NAME CDATA #REQUIRED>
      <!ATTLIST METRICS SUM CDATA #REQUIRED>
      <!ATTLIST METRICS NUM CDATA #REQUIRED>
      <!ATTLIST METRICS TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRICS UNITS CDATA #IMPLIED>
      <!ATTLIST METRICS SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRICS SOURCE (gmond) 'gmond'>
]>
<GANGLIA_XML VERSION="3.7.2" SOURCE="gmetad">
<GRID NAME="unspecified" AUTHORITY="http://concertim-dev2/ganglia/" LOCALTIME="1695290644">
<CLUSTER NAME="unspecified" LOCALTIME="1695290634" OWNER="unspecified" LATLONG="unspecified" URL="unspecified">
<HOST NAME="device:1" IP="" REPORTED="1695290530" TN="113" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="113" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.capacity" VAL="10" TYPE="int32" UNITS="" TN="125" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8913" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.211200" TYPE="double" UNITS="cups" TN="118" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="15" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:4" IP="" REPORTED="1695290530" TN="113" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="113" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.capacity" VAL="10" TYPE="int32" UNITS="" TN="125" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8930" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="6.651200" TYPE="double" UNITS="cups" TN="118" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="21" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:3" IP="" REPORTED="1695290530" TN="113" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="113" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.capacity" VAL="10" TYPE="int32" UNITS="" TN="125" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8971" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="4.015400" TYPE="double" UNITS="cups" TN="118" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="13" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:2" IP="" REPORTED="1695290530" TN="113" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="113" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.capacity" VAL="10" TYPE="int32" UNITS="" TN="125" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9034" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="0.190600" TYPE="double" UNITS="cups" TN="118" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="22" TYPE="int32" UNITS="" TN="157" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
</CLUSTER>
</GRID>
</GANGLIA_XML>
