<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE GANGLIA_XML [
   <!ELEMENT GANGLIA_XML (GRID|CLUSTER|HOST)*>
      <!ATTLIST GANGLIA_XML VERSION CDATA #REQUIRED>
      <!ATTLIST GANGLIA_XML SOURCE CDATA #REQUIRED>
   <!ELEMENT GRID (CLUSTER | GRID | HOSTS | METRICS)*>
      <!ATTLIST GRID NAME CDATA #REQUIRED>
      <!ATTLIST GRID AUTHORITY CDATA #REQUIRED>
      <!ATTLIST GRID LOCALTIME CDATA #IMPLIED>
   <!ELEMENT CLUSTER (HOST | HOSTS | METRICS)*>
      <!ATTLIST CLUSTER NAME CDATA #REQUIRED>
      <!ATTLIST CLUSTER OWNER CDATA #IMPLIED>
      <!ATTLIST CLUSTER LATLONG CDATA #IMPLIED>
      <!ATTLIST CLUSTER URL CDATA #IMPLIED>
      <!ATTLIST CLUSTER LOCALTIME CDATA #REQUIRED>
   <!ELEMENT HOST (METRIC)*>
      <!ATTLIST HOST NAME CDATA #REQUIRED>
      <!ATTLIST HOST IP CDATA #REQUIRED>
      <!ATTLIST HOST LOCATION CDATA #IMPLIED>
      <!ATTLIST HOST TAGS CDATA #IMPLIED>
      <!ATTLIST HOST REPORTED CDATA #REQUIRED>
      <!ATTLIST HOST TN CDATA #IMPLIED>
      <!ATTLIST HOST TMAX CDATA #IMPLIED>
      <!ATTLIST HOST DMAX CDATA #IMPLIED>
      <!ATTLIST HOST GMOND_STARTED CDATA #IMPLIED>
   <!ELEMENT METRIC (EXTRA_DATA*)>
      <!ATTLIST METRIC NAME CDATA #REQUIRED>
      <!ATTLIST METRIC VAL CDATA #REQUIRED>
      <!ATTLIST METRIC TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRIC UNITS CDATA #IMPLIED>
      <!ATTLIST METRIC TN CDATA #IMPLIED>
      <!ATTLIST METRIC TMAX CDATA #IMPLIED>
      <!ATTLIST METRIC DMAX CDATA #IMPLIED>
      <!ATTLIST METRIC SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRIC SOURCE (gmond) 'gmond'>
   <!ELEMENT EXTRA_DATA (EXTRA_ELEMENT*)>
   <!ELEMENT EXTRA_ELEMENT EMPTY>
      <!ATTLIST EXTRA_ELEMENT NAME CDATA #REQUIRED>
      <!ATTLIST EXTRA_ELEMENT VAL CDATA #REQUIRED>
   <!ELEMENT HOSTS EMPTY>
      <!ATTLIST HOSTS UP CDATA #REQUIRED>
      <!ATTLIST HOSTS DOWN CDATA #REQUIRED>
      <!ATTLIST HOSTS SOURCE (gmond | gmetad) #REQUIRED>
   <!ELEMENT METRICS (EXTRA_DATA*)>
      <!ATTLIST METRICS NAME CDATA #REQUIRED>
      <!ATTLIST METRICS SUM CDATA #REQUIRED>
      <!ATTLIST METRICS NUM CDATA #REQUIRED>
      <!ATTLIST METRICS TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRICS UNITS CDATA #IMPLIED>
      <!ATTLIST METRICS SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRICS SOURCE (gmond) 'gmond'>
]>
<GANGLIA_XML VERSION="3.7.2" SOURCE="gmetad">
<GRID NAME="unspecified" AUTHORITY="http://concertim-dev2/ganglia/" LOCALTIME="1695290897">
<CLUSTER NAME="unspecified" LOCALTIME="1695290891" OWNER="unspecified" LATLONG="unspecified" URL="unspecified">
<HOST NAME="device:49" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8964" TYPE="int32" UNITS="" TN="77" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="0.254300" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="21" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:26" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8967" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="6.833000" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="21" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:11" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9074" TYPE="int32" UNITS="" TN="79" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.395900" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="20" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:94" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9084" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.362700" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="20" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:6" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9081" TYPE="int32" UNITS="" TN="79" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.270700" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="15" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:91" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8986" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.754400" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="15" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:84" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9064" TYPE="int32" UNITS="" TN="75" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="4.208000" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="24" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:28" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9001" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="3.330600" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="12" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:70" IP="" REPORTED="1695290851" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9077" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="0.647700" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:65" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9087" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="8.712900" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:1" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.capacity" VAL="10" TYPE="int32" UNITS="" TN="378" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8943" TYPE="int32" UNITS="" TN="79" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="1.622800" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="20" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:53" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9018" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="3.944900" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:42" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8905" TYPE="int32" UNITS="" TN="77" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="2.666900" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="19" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:104" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9042" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="6.055200" TYPE="double" UNITS="cups" TN="53" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="16" TYPE="int32" UNITS="" TN="63" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:18" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9059" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.492400" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="22" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:110" IP="" REPORTED="1695290852" TN="44" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="44" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8933" TYPE="int32" UNITS="" TN="73" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="8.471200" TYPE="double" UNITS="cups" TN="53" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="17" TYPE="int32" UNITS="" TN="63" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:75" IP="" REPORTED="1695290851" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8975" TYPE="int32" UNITS="" TN="75" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.689800" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="16" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:60" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8962" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="4.522900" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="15" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:58" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9083" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="4.148800" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:45" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8968" TYPE="int32" UNITS="" TN="77" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.316200" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="22" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:32" IP="" REPORTED="1695290850" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8978" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.489400" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:101" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8969" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="0.987500" TYPE="double" UNITS="cups" TN="53" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="12" TYPE="int32" UNITS="" TN="63" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:22" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9055" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.969600" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="23" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:15" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8933" TYPE="int32" UNITS="" TN="78" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="2.421000" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="24" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:48" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8998" TYPE="int32" UNITS="" TN="77" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="6.236400" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="19" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:12" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9083" TYPE="int32" UNITS="" TN="79" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="8.497600" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="22" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:95" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8953" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.033600" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="24" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:69" IP="" REPORTED="1695290851" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8979" TYPE="int32" UNITS="" TN="76" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="3.661100" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="18" TYPE="int32" UNITS="" TN="64" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:38" IP="" REPORTED="1695290851" TN="46" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="46" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8937" TYPE="int32" UNITS="" TN="77" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="5.515100" TYPE="double" UNITS="cups" TN="55" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="21" TYPE="int32" UNITS="" TN="65" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:5" IP="" REPORTED="1695290850" TN="47" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="47" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="8988" TYPE="int32" UNITS="" TN="79" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="7.858500" TYPE="double" UNITS="cups" TN="56" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.level" VAL="17" TYPE="int32" UNITS="" TN="66" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
</HOST>
<HOST NAME="device:92" IP="" REPORTED="1695290852" TN="45" TMAX="60" DMAX="180" LOCATION="unspecified" GMOND_STARTED="0" TAGS="unspecified">
<METRIC NAME="caffeine.more" VAL="yes" TYPE="string" UNITS="" TN="45" TMAX="60" DMAX="3600" SLOPE="zero" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="power.level" VAL="9085" TYPE="int32" UNITS="" TN="74" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="caffeine.consumption" VAL="4.007800" TYPE="double" UNITS="cups" TN="54" TMAX="60" DMAX="3600" SLOPE="both" SOURCE="ct-metric-reporting-daemon">
<EXTRA_DATA>
</EXTRA_DATA>
</METRIC>